// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHB8BCK37CwvvwpdvSilSKMChMXMX0_Ew',
    appId: '1:298612751636:web:801005a2a43d0ecd821601',
    messagingSenderId: '298612751636',
    projectId: 'beermonopolynotifications',
    authDomain: 'beermonopolynotifications.firebaseapp.com',
    storageBucket: 'beermonopolynotifications.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI25lJoDKVcG6nJ6ot_BEk44phlOnsPVk',
    appId: '1:298612751636:android:ad73b7b0c6af7542821601',
    messagingSenderId: '298612751636',
    projectId: 'beermonopolynotifications',
    storageBucket: 'beermonopolynotifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXvk4ONOVkWltNVYPGtwr5r3x6XxnSAak',
    appId: '1:298612751636:ios:ca572ee6f6fd04ab821601',
    messagingSenderId: '298612751636',
    projectId: 'beermonopolynotifications',
    storageBucket: 'beermonopolynotifications.appspot.com',
    iosClientId: '298612751636-u2thkfq60087dnkml3ectaeqbe752rms.apps.googleusercontent.com',
    iosBundleId: 'com.beermonopoly.olmonopolet',
  );
}
