import "../../Fastfile"

default_platform(:android)

platform :android do

  lane :build do |options|
    verify_env(envs: [
      "APP_PACKAGE_NAME"
    ])

    unless File.exist?(google_service_account_json_path)
      UI.user_error!("google_service_account.json file not found. Please add it to the root of the flutter project. See https://docs.fastlane.tools/actions/supply/")
    end

    normalized_build_number = normalize_optional(options[:build_number])
    normalized_version_number = normalize_optional(options[:version_number])
    version_number = normalized_version_number || get_version_from_pubspec()

    if !is_ci && normalized_version_number.nil?
      continue = UI.confirm("Deploying version #{version_number} (from pubspec.yaml) to Play Store. Continue?")

      unless continue
        UI.user_error!("Aborted")
      end
    end

    build_number = normalized_build_number || get_build_number("playstore")

    build_flutter_app(
      type: options[:type] || "appbundle",
      no_codesign: options[:no_codesign],
      config_only: options[:config_only],
      build_number: build_number,
      version_number: version_number,
      store: "playstore"
    )
  end

  # Release to Play Store using Fastlane Supply (https://docs.fastlane.tools/actions/supply/)
  desc "Release to Play Store"
  lane :release_play_store do |options|
    pubspec_version_number = get_version_from_pubspec()
    ci_tag_version_number = get_version_from_ci_tag()
    requested_version_number = normalize_optional(options[:version_number]) || ci_tag_version_number
    version_number = choose_version_number(
      requested_version_number,
      pubspec_version_number,
      nil
    )

    if normalize_optional(options[:version_number]).nil? && !ci_tag_version_number.nil?
      UI.message("No explicit version_number provided. Using tag version #{ci_tag_version_number}.")
    end

    build(
      no_codesign: options[:no_codesign],
      config_only: options[:config_only],
      build_number: options[:build_number],
      version_number: version_number
    )

    supply(
      track: 'internal',
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: google_service_account_json_path,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  # Release to Play Store using Firebase App Distribution (https://docs.fastlane.tools/actions/firebase_app_distribution/)
  desc "Release to Play Store using Firebase App Distribution"
  lane :release_play_store_using_firebase do |options|
    build(
      type: 'apk',
      no_codesign: options[:no_codesign],
      config_only: options[:config_only],
      build_number: options[:build_number],
      version_number: options[:version_number]
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_path: "#{root_path}/build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: google_service_account_json_path,
      debug: true
    )
  end
end