const Map<String, String> beermonopolyStyleList = {
  'Annet': 'adambier,altbier,brett,burton,tan,chilli,cream ale,festbier,grape ale,'
      'happoshu,historical,honey beer,kellerbier,koji,kvass,lichtenhainer,'
      'malt beer,mild,pumpkin,rauchbier,roggenbier,root beer,rye beer,schwarzbier,'
      'smoked beer,shandy,scotch ale,scottish,steinbier,spiced / herbed,strong ale,table beer,zoigl',
  'Barleywine': 'barleywine',
  'Belgisk': 'belgian',
  'Blonde': 'blonde',
  'Bokk': 'bock',
  'Brown Ale': 'brown',
  'Dark Ale': 'dark ale',
  'Farmhouse Ale': 'farmhouse ale',
  'Glutenfri': 'gluten-free',
  'Hvete': 'wheat beer',
  'IPA': 'ipa',
  'Juleøl': 'winter',
  'Kölsch': 'kölsch',
  'Lager': 'lager',
  'Mjød': 'mead',
  'Old Ale': 'old ale, traditional ale',
  'Pale Ale': 'pale ale',
  'Pilsner': 'pilsner',
  'Porter': 'porter',
  'Red Ale': 'red ale -',
  'Sider': 'cider',
  'Stout': 'stout',
  'Surøl': 'sour,wild ale,lambic,fruit beer',
};

const List<String> untappdStyleList = [
  'Altbier',
  'Australian Sparkling Ale',
  'Barleywine - American',
  'Barleywine - English',
  'Barleywine - Other',
  'Belgian Blonde',
  'Belgian Dubbel',
  'Belgian Enkel / Patersbier',
  'Belgian Quadrupel',
  'Belgian Strong Dark Ale',
  'Belgian Strong Golden Ale',
  'Belgian Tripel',
  'Bitter - Best',
  'Bitter - Extra Special / Strong (ESB)',
  'Bitter - Session / Ordinary',
  'Bière de Champagne / Bière Brut',
  'Blonde Ale',
  'Bock - Doppelbock',
  'Bock - Eisbock',
  'Bock - Hell / Maibock / Lentebock',
  'Bock - Single / Traditional',
  'Bock - Weizenbock',
  'Bock - Weizendoppelbock',
  'Brett Beer',
  'Brown Ale - American',
  'Brown Ale - Belgian',
  'Brown Ale - English',
  'Brown Ale - Imperial / Double',
  'Brown Ale - Other',
  'California Common',
  'Chilli / Chile Beer',
  'Cider - Dry',
  'Cider - Graff',
  'Cider - Herbed / Spiced / Hopped',
  'Cider - Ice / Applewine',
  'Cider - Other Fruit',
  'Cider - Perry',
  'Cider - Rosé',
  'Cider - Sweet',
  'Cider - Traditional / Apfelwein',
  'Corn Beer / Chicha De Jora',
  'Cream Ale',
  'Dark Ale',
  'Farmhouse Ale - Bière de Coupage',
  'Farmhouse Ale - Bière de Garde',
  'Farmhouse Ale - Bière de Mars',
  'Farmhouse Ale - Grisette',
  'Farmhouse Ale - Other',
  'Farmhouse Ale - Sahti',
  'Farmhouse Ale - Saison',
  'Festbier',
  'Flavored Malt Beverage',
  'Freeze-Distilled Beer',
  'Fruit Beer',
  'Gluten-Free',
  'Golden Ale',
  'Grape Ale - Italian',
  'Grape Ale - Other',
  'Grodziskie / Grätzer',
  'Happoshu',
  'Hard Ginger Beer',
  'Hard Kombucha',
  'Hard Seltzer',
  'Historical Beer - Adambier',
  'Historical Beer - Berliner Braunbier',
  'Historical Beer - Burton Ale',
  'Historical Beer - Dampfbier',
  'Historical Beer - Gruit / Ancient Herbed Ale',
  'Historical Beer - Kentucky Common',
  'Historical Beer - Kottbusser',
  'Historical Beer - Lichtenhainer',
  'Historical Beer - Mumme',
  'Historical Beer - Other',
  'Historical Beer - Steinbier',
  'Historical Beer - Zoigl',
  'Honey Beer',
  'IPA - American',
  'IPA - Belgian',
  'IPA - Black / Cascadian Dark Ale',
  'IPA - Brett',
  'IPA - Brut',
  'IPA - English',
  'IPA - Farmhouse',
  'IPA - Imperial / Double',
  'IPA - Imperial / Double Black',
  'IPA - Imperial / Double Milkshake',
  'IPA - Imperial / Double New England / Hazy',
  'IPA - International',
  'IPA - Milkshake',
  'IPA - New England / Hazy',
  'IPA - New Zealand',
  'IPA - Other',
  'IPA - Quadruple',
  'IPA - Red',
  'IPA - Rye',
  'IPA - Session',
  'IPA - Sour',
  'IPA - Triple',
  'IPA - Triple New England / Hazy',
  'IPA - White',
  'Kellerbier / Zwickelbier',
  'Koji / Ginjo Beer',
  'Kvass',
  'Kölsch',
  'Lager - Amber',
  'Lager - American',
  'Lager - American Amber / Red',
  'Lager - American Light',
  'Lager - Dark',
  'Lager - Dortmunder / Export',
  'Lager - Helles',
  'Lager - IPL (India Pale Lager)',
  'Lager - Japanese Rice',
  'Lager - Leichtbier',
  'Lager - Mexican',
  'Lager - Munich Dunkel',
  'Lager - Pale',
  'Lager - Red',
  'Lager - Strong',
  'Lager - Vienna',
  'Lager - Winter',
  'Lambic - Faro',
  'Lambic - Framboise',
  'Lambic - Fruit',
  'Lambic - Gueuze',
  'Lambic - Kriek',
  'Lambic - Other',
  'Lambic - Traditional',
  'Malt Beer',
  'Malt Liquor',
  'Mead - Acerglyn / Maple Wine',
  'Mead - Bochet',
  'Mead - Braggot',
  'Mead - Cyser',
  'Mead - Melomel',
  'Mead - Metheglin',
  'Mead - Other',
  'Mead - Pyment',
  'Mead - Session / Short',
  'Mead - Traditional',
  'Mild - Dark',
  'Mild - Light',
  'Mild - Other',
  'Märzen',
  'Non-Alcoholic Beer',
  'Old Ale',
  'Pale Ale - American',
  'Pale Ale - Australian',
  'Pale Ale - Belgian',
  'Pale Ale - English',
  'Pale Ale - International',
  'Pale Ale - Milkshake',
  'Pale Ale - New England / Hazy',
  'Pale Ale - New Zealand',
  'Pale Ale - Other',
  'Pale Ale - XPA (Extra Pale)',
  'Pilsner - Czech',
  'Pilsner - German',
  'Pilsner - Imperial / Double',
  'Pilsner - Italian',
  'Pilsner - Other',
  'Porter - American',
  'Porter - Baltic',
  'Porter - Coffee',
  'Porter - English',
  'Porter - Imperial / Double',
  'Porter - Imperial / Double Baltic',
  'Porter - Imperial / Double Coffee',
  'Porter - Other',
  'Pumpkin / Yam Beer',
  'Rauchbier',
  'Red Ale - American Amber / Red',
  'Red Ale - Imperial / Double',
  'Red Ale - Irish',
  'Red Ale - Other',
  'Roggenbier',
  'Root Beer',
  'Rye Beer',
  'Rye Wine',
  'Schwarzbier',
  'Scotch Ale / Wee Heavy',
  'Scottish Ale',
  'Scottish Export Ale',
  'Shandy / Radler',
  'Smoked Beer',
  'Sour - Berliner Weisse',
  'Sour - Flanders Oud Bruin',
  'Sour - Flanders Red Ale',
  'Sour - Fruited',
  'Sour - Fruited Berliner Weisse',
  'Sour - Fruited Gose',
  'Sour - Other',
  'Sour - Other Gose',
  'Sour - Smoothie / Pastry',
  'Sour - Traditional Gose',
  'Specialty Grain',
  'Spiced / Herbed Beer',
  'Stout - American',
  'Stout - Coffee',
  'Stout - English',
  'Stout - Foreign / Export',
  'Stout - Imperial / Double',
  'Stout - Imperial / Double Coffee',
  'Stout - Imperial / Double Milk',
  'Stout - Imperial / Double Oatmeal',
  'Stout - Imperial / Double Pastry',
  'Stout - Imperial / Double White / Golden',
  'Stout - Irish Dry',
  'Stout - Milk / Sweet',
  'Stout - Oatmeal',
  'Stout - Other',
  'Stout - Oyster',
  'Stout - Pastry',
  'Stout - Russian Imperial',
  'Stout - White / Golden',
  'Strong Ale - American',
  'Strong Ale - English',
  'Strong Ale - Other',
  'Table Beer',
  'Traditional Ale',
  'Wheat Beer - American Pale Wheat',
  'Wheat Beer - Dunkelweizen',
  'Wheat Beer - Hefeweizen',
  'Wheat Beer - Hefeweizen Light / Leicht',
  'Wheat Beer - Hopfenweisse',
  'Wheat Beer - Kristallweizen',
  'Wheat Beer - Other',
  'Wheat Beer - Wheat Wine',
  'Wheat Beer - Witbier / Blanche',
  'Wild Ale - American',
  'Wild Ale - Other',
  'Winter Ale',
  'Winter Warmer',
];

const Map<String, String> countryList = {
  'Argentina': 'AR',
  'Australia': 'AU',
  'Belgia': 'BE',
  'Brasil': 'BR',
  'Bulgaria': "BG",
  'Canada': 'CA',
  'Danmark': 'DK',
  'Den europeiske union': 'EU',
  'England': 'GB',
  'Estland': 'EE',
  'Finland': "FI",
  'Frankrike': 'FR',
  'Færøyene': 'FO',
  'Georgia': 'GE',
  'Hellas': 'GR',
  'India': 'IN',
  'Irland': 'IE',
  'Island': 'IS',
  'Italia': 'IT',
  'Japan': 'JP',
  'Kina': 'CN',
  'Kroatia': 'HR',
  'Latvia': 'LV',
  'Libanon': 'LB',
  'Litauen': 'LT',
  'Mexico': 'MX',
  'Nederland': 'NL',
  'New Zealand': 'NZ',
  'Nord Irland': "GB",
  'Norge': 'NO',
  'Palestina': 'PS',
  'Peru': 'PE',
  'Polen': 'PL',
  'Portugal': 'PT',
  'Russland': 'RU',
  'Serbia': 'RS',
  'Singapore': 'SG',
  'Skottland': 'GB',
  'Spania': 'ES',
  'Storbritannia': 'GB',
  'Sveits': 'CH',
  'Sverige': 'SE',
  'Sør-Afrika': 'ZA',
  'Thailand': 'TH',
  'Tsjekkia': 'CZ',
  'Tyrkia': 'TR',
  'Tyskland': 'DE',
  'USA': 'US',
  'Ungarn': 'HU',
  'Ukraina': 'UA',
  'Wales': 'GB',
  'Østerrike': 'AT',
};

const Map<String, String> sortList = {
  'Alkohol - Høy til lav': '-abv',
  'Alkohol - Lav til høy': 'abv',
  'Bryggeri - Stigende': 'brewery',
  'Bryggeri - Synkende': '-brewery',
  'Dato lagt til - Nyeste først': '-created_at',
  'Dato lagt til - Eldste først': 'created_at',
  'Global rating - Høy til lav': '-rating',
  'Global rating - Lav til høy': 'rating',
  'Navn - A til Å': 'vmp_name',
  'Navn - Å til A': '-vmp_name',
  'Pris - Høy til lav': '-price',
  'Pris - Lav til høy': 'price',
  'Pris per liter - Høy til lav': '-price_per_volume',
  'Pris per liter - Lav til høy': 'price_per_volume',
};

const Map<String, String> sortListAuth = {
  'Alkohol - Høy til lav': '-abv',
  'Alkohol - Lav til høy': 'abv',
  'Bryggeri - Stigende': 'brewery',
  'Bryggeri - Synkende': '-brewery',
  'Dato lagt til - Nyeste først': '-created_at',
  'Dato lagt til - Eldste først': 'created_at',
  'Din rating - Høy til lav': '-checkin__rating',
  'Din rating - Lav til høy': 'checkin__rating',
  'Global rating - Høy til lav': '-rating',
  'Global rating - Lav til høy': 'rating',
  'Navn - A til Å': 'vmp_name',
  'Navn - Å til A': '-vmp_name',
  'Pris - Høy til lav': '-price',
  'Pris - Lav til høy': 'price',
  'Pris per liter - Høy til lav': '-price_per_volume',
  'Pris per liter - Lav til høy': 'price_per_volume',
};

const Map<String, String> productSelectionAbrevationList = {
  'Basisutvalget': 'Basis',
  'Bestillingsutvalget': 'BU',
  'Partiutvalget': 'Parti',
  'Tilleggsutvalget': 'TU',
};

const List<Map<String, String>> productSelectionList = [
  {'Basisutvalget': 'basisutvalget'},
  {'Bestillingsutvalget': 'bestillingsutvalget'},
  {'Partiutvalget': 'partiutvalget'},
  {'Spesialutvalget': 'spesialutvalg'},
  {'Tilleggsutvalget': 'tilleggsutvalget'},
];

const List<Map<String, String>> excludeAllergensList = [
  {'Gluten': 'gluten, bygg, spelt, hvete, havre, rug'},
  {'Laktose': 'laktose, melk'},
  {'Nøtter': 'nøtter, peanøtt, hasselnøtt, valnøtt, nøtt'},
  {'Sulfitt': 'sulfitt'},
];

const List<String> checkinList = [
  'Alle',
  'Innsjekket',
  'Ikke innsjekket',
];

const List<String> wishlistList = [
  'Alle',
  'I ønskeliste',
  'Ikke i ønskeliste',
];

const List<String> styleChoiceList = [
  'Ølmonopolet',
  'Untappd',
];

const List<String> deliveryList = ['Levering til butikk', 'Levering på posten'];
